config/routes.rb
GameApp::Application.routes.draw do
  resources :games do
    member do
      resources :moves, only: [:create]
      match :accept
      match :decline
    end
  end

  resources :users do 
    member do
      match :overview
      match :opponents
      match :challenges
    end
  end

  



  resources :sessions, only: [:new, :create, :destroy]

  get "/login", to: "sessions#new"

  root to: "users#overview"
end

app/models/game.rb
class Game < ActiveRecord::Base

  WIN_SETS = [%w[1-1 1-2 1-3], %w[2-1 2-2 2-3], %w[3-1 3-2 3-3], %w[1-1 2-1 3-1], %w[1-2 2-2 3-2], %w[1-3 2-3 3-3], %w[1-1 2-2 3-3], %w[3-1 2-2 1-3]].map(&:to_set)

  attr_accessible :declined, :draw, :finished, :loser, :winner, :player_1, :player_2

  has_many :moves
  has_many :users, through: :moves

  belongs_to :player_1, class_name: "User"
  belongs_to :player_2, class_name: "User"

  belongs_to :winner, class_name: "User"
  belongs_to :loser, class_name: "User"

  def self.in_progress
    where(finished: false).all
  end

  def self.game_won?(game)
    move_set = moves.where(user_id: @current_user, game_id: game.id).map(&:placement).to_set
    WIN_SETS.any? do |win_set|
      move_set.superset? win_set
    end
  end
  

end

app/models/move.rb
class Move < ActiveRecord::Base

  
  
  attr_accessible :move_no, :placement, :game, :game_id, :user, :user_id

  belongs_to :user
  belongs_to :game 

  validates_uniqueness_of :move_no, scope: :game_id

  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates :email, presence: true, uniqueness: true
  attr_accessible :email, :password, :password_confirmation, :user_name

  has_many :moves
  has_many :users, through: :moves

  has_many :games_as_player_1, class_name: "Game", foreign_key: "player_1"
  has_many :games_as_player_2, class_name: "Game", foreign_key: "player_2"

  has_many :won_games, class_name: "Game", foreign_key: "winner_id"
  has_many :lost_games, class_name: "Game", foreign_key: "loser_id"

  def self.opponents_of_user(excluded_user)
    where("id != ?", excluded_user.id).all
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user 

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_path, alert: "You cannot access this page"
  # end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  private

  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged in to access this page"
      redirect_to login_path
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    #@games = Game.all
  end

  # Called when a user starts a game with computer or user
  # def new
  #   @game = Game.new
  # end

  # The game being played
  def show
    @game = Game.find params[:id]
    @moves = @game.moves
  end

  # 
  def create
    @game = Game.new
    @game.player_1 = current_user
    @game.player_2 = User.find(params[:player_2])
    @game.finished = false
    @game.save

    redirect_to @game
  end

  # Used to edit the game fields (e.g. win, lose etc.)
  def edit
    @game = Game.find(params[:id])
  end

  # When a user declines a challenge - the finished field is set to true.
  # Can no longer be accessed by anyone.
  def decline
    @game = Game.find(params[:id])
    @game.declined = true
    @game.finished = true
    redirect_to challenges_user_path(current_user)
  end

  def accept
    @game = Game.find(params[:id])
    @game.declined = false
    redirect_to game_path(@game)
  end

end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  def create
    @game = Game.find params[:id]
    @user_id = current_user
    @move = Move.new
    @last_move_in_game = Move.where(game_id: @game).last

    if @last_move_in_game
      new_move = @last_move_in_game.move_no + 1
    else
      new_move = 1
    end

    @move.move_no = new_move
    @move.placement = params[:placement]
    @move.user_id = current_user.id
    @move.game_id = @game.id   

    @move.save!


    # if Game.game_won?(@game)
    #   @game.finished = true
    #   @winner_id = current_user.id
    #   @game.save!
    # end

    redirect_to game_path(@game)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  # Sign in
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      # user is authenticated
      session[:user_id] = user.id
      redirect_to root_path, notice: "You have successfully signed in"
    else
      # wrong credentials
      flash.now[:alert] = "Invalid Login Credentials"
      render :new
    end
  end

  # Sign out
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, only: :show

  def index
  #   @users = User.all
  end

  def new
    @user = User.new
  end

  # User sign up
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  # Access overview, opponents and challenges
  def show
    @user = current_user
    #authorize! :show, @user
  end

  def overview
    @c_wins = Game.where(player_2_id: 1, player_1_id: current_user.id, winner_id: current_user.id).count
    @c_losses = Game.where(player_2_id: 1, player_1_id: current_user.id, loser_id: current_user.id).count
    @c_draws = Game.where(player_2_id: 1, player_1_id: current_user.id, draw: true).count
    @wins = Game.where(winner_id: current_user.id).count
    @losses = Game.where(loser_id: current_user.id).count
    @draw = Game.where("(player_1_id = #{current_user.id} OR player_2_id = #{current_user.id}) AND draw= true").count
    @u_wins = @wins - @c_wins
    @u_losses = @losses - @c_losses
    @u_draws = @draw - @c_draws


    @partial_name = "overview"
    render :show
  end

  def opponents
    opponents = User.opponents_of_user(current_user)
    games = Game.in_progress

    # Create games in progress method.

    @opponents = opponents.each_with_object({}) do |opponent, hash|
      shared_game = games.detect do |game|
        cu_game = game.player_1_id == current_user.id && game.player_2_id == opponent.id
        op_game = game.player_1_id == opponent.id && game.player_2_id == current_user.id
        cu_game || op_game
      end
      hash[opponent] = shared_game
    end

    @partial_name = "opponents"
    render :show
  end

  def challenges
    Game.all.each do |game|
      @game = game.where(declined: nil, player_2_id: params[:id])
      @opp = User.find(@game.player_1_id)
      @opponent = @opp.user_name
    end
    @partial_name = "challenges"
    render :show
  end

  # def current_user_game
  #   Game.all.each do |game|
  #     if game.player_1_id = params[:id] || game.player_2_id = params[:id]
  #     end
  #   end
  # end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_square(row, col, moves)
    symbol = get_symbol(row, col, moves)
    case symbol
    when "X", "O"
      cell_html(symbol)
    else
      link_to moves_path(params[:id], placement: "#{row}-#{col}"), method: :post do
        cell_html(symbol)
      end
    end
  end

  def cell_html(symbol)
    html = <<-HTML_SNIPPET
      <div class="cell">
        #{symbol}
      </div>
    HTML_SNIPPET
    html.html_safe
  end


  def get_symbol(row, col, moves)
    move = moves.detect { |m| m.placement == "#{row}-#{col}" }
    if move
      move.move_no.odd? ? "X" : "O"
    else
      "?"
    end
  end

  # def ai
  #   # if move_no.even?
  #   # placement = any symbol with ?
  #   # user_id = 1
  # end 

end

app/views/games/show.html.erb
  <div class="game_container ">
    <% 1.upto(3) do |row| %>
      <% 1.upto(3) do |col| %>
        <%= render_square(row, col, @moves) %>
      <% end %>
    <% end %>
  </div>

<div class="footer">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <% if current_user %>
      Hello, <%= current_user.user_name %>
      <%= link_to "logout", session_path(session), method: :delete, confirm: "Are you sure you want to log out?", :class => 'right_button' %>
      <%= link_to "Overview", overview_user_path(current_user), :class => 'left_button' %>
      <%= link_to "Opponents", opponents_user_path(current_user), :class => 'left_button' %>
    <% else %>
      <%= link_to "Login", login_path, :class => 'button' %>
      <%= link_to "Sign up", new_user_path, :class => 'button' %>
    <% end %>
  <% flash.each do |name, message| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= message %>
  <% end %>

    </div>
    
  </div>
  </div>
  <div>
  <%= yield %>
  </div>
  <div class="footer">
    <h1>Friendly Noughts and Crosses</h1>
  </div>
</body>

</html>

app/views/users/_challenges.html.erb
<div id="content">
<% if @games %>
  <div id="games">
    <% @games.each do |game| %>
      <div class="game">
        <%= "#{@opponent} has challenged you to a game!" %>  
            <%= link_to "Accept", accept_game_path(@game) %> | 
            <%= link_to "Decline", decline_game_path(@game) %>         
      </div>
    <% end %>
  </div>

<% else%>
  <p>You don't have any challenges. Why not challenge someone?</p>
  <%= link_to "New Game", new_game_path %>
<% end %>
</div>

app/views/users/_form.html.erb
<div>
<%= form_for @user do |f| %>
  <p>
    <%= @user.errors.full_messages.join(", ") unless @user.errors.empty? %>
  </p>
  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button'  %>
  </div>

<% end %>
</div>

app/views/users/_opponents.html.erb
<div class="content">
<% @opponents.each do |opponent, shared_game| %>
<br>
  <h3><%= opponent.user_name %></h3>
  <div class="opponent">
    <% if shared_game %>
      <%= link_to "Current Game", game_path(shared_game), :class => 'game_button'  %>
      
    <% else %>
      <%= link_to "New Game", games_path(player_2: opponent.id), method: :post, :class => 'game_button' %>
      
    <% end %>
  </div>
<% end %>
</div>

app/views/users/_overview.html.erb
<div class="container">
  <div class="content">

  <table>
    <thead>
      <tr>
        <th></th>
        <th>win</th>
        <th>lose</th>
        <th>draw</th>
      </tr>
     </thead>
     <tbody>
      <tr>
        <td>vs. Computer</td>
        <td><%= @c_wins %></td>
        <td><%= @c_losses %></td>
        <td><%= @c_draws %></td>
      </tr>
      <tr>
        <td>vs. User</td>
        <td><%= @u_wins %></td>
        <td><%= @u_losses %></td>
        <td><%= @u_draws %></td>
      </tr>
      <tr>
        <td>Total</td>
        <td><%= @wins %></td>
        <td><%= @losses %></td>
        <td><%= @draw %></td>
      </tr>
    </tbody>
  </table>

  </div>
</div>

<footer>
</footer>

app/views/users/new.html.erb
<div class="content">
<h2>Sign up</h2>

<%= render "form" , user: @user %>
</div>

app/views/users/show.html.erb
<%= render @partial_name || "overview" %>